### ISSUE TITLE
Wrong key is accessed from dictionary for jwt. `access_token` instead of `id_token`.

### ISSUE THREAD

**Issue by VisheshMangla2711** [googleapis/google-auth-library-python#1066]
#### Environment details

  - OS: Mac
  - Python version: 3.9.13
  - pip version:22.1.2
  - `google-auth` version: 2.6.6

**Code**
```

def get_message_api(
    config, google_credentials, receiver_email, sender_email, email_html_body
) -> None:
    from simplegmail import Gmail
    class Temp(Gmail):
        def __init__(self, google_credentials):
            """monkeypatch till issue resolves of not accepting service account"""
            from googleapiclient.discovery import build

            self.creds = google_credentials
            self._service = build("gmail", "v1", credentials=self.creds)

        @property
        def service(self):
            return self._service

    gmail = Temp(google_credentials)
    params = {
        "subject": config["EMAIL"]["subject"],
        "sender": sender_email,
        "cc": config["EMAIL"]["cc"] or [],
        "bcc": config["EMAIL"]["bcc"] or [],
        "to": receiver_email,
        "msg_html": css_inline.inline(email_html_body),
        "msg_plain": config["EMAIL"]["plain_body"],
        "attachments": (
            ["bot_api_problems.xlsx", "bot.pdf"] + config["EMAIL"]["attachments"]
        ),
        "signature": True,
    }
    _ = gmail.send_message(**params)
```

**Error**
The [_client.py](https://github.com/googleapis/google-auth-library-python/blob/main/google/oauth2/_client.py#L220) file extracts the key `access_token` whereas in the request it's getting `id_token`.

```
Traceback (most recent call last):
  File "/Users/netomi/Desktop/msgai-data-analyst-code/venv-botperf/lib/python3.9/site-packages/google/oauth2/_client.py", line 196, in jwt_grant
    access_token = response_data["access_token"]
KeyError: 'access_token'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/netomi/Desktop/msgai-data-analyst-code/DailyMonitor_BotPerformance/__main__.py", line 18, in <module>
    raise e
  File "/Users/netomi/Desktop/msgai-data-analyst-code/DailyMonitor_BotPerformance/__main__.py", line 15, in <module>
    print("File saved at: ", main(config))
  File "/Users/netomi/Desktop/msgai-data-analyst-code/DailyMonitor_BotPerformance/main.py", line 18, in main
    paths_to_file = mail_sender(config, google_credentials)
  File "/Users/netomi/Desktop/msgai-data-analyst-code/DailyMonitor_BotPerformance/functions/mailSender.py", line 416, in mail_sender
    message = get_message_api(
  File "/Users/netomi/Desktop/msgai-data-analyst-code/DailyMonitor_BotPerformance/functions/mailSender.py", line 455, in get_message_api
    _ = gmail.send_message(**params)
  File "/Users/netomi/Desktop/msgai-data-analyst-code/venv-botperf/lib/python3.9/site-packages/simplegmail/gmail.py", line 152, in send_message
    msg = self._create_message(
  File "/Users/netomi/Desktop/msgai-data-analyst-code/venv-botperf/lib/python3.9/site-packages/simplegmail/gmail.py", line 879, in _create_message
    account_sig = self._get_alias_info(address, user_id)['signature']
  File "/Users/netomi/Desktop/msgai-data-analyst-code/venv-botperf/lib/python3.9/site-packages/simplegmail/gmail.py", line 988, in _get_alias_info
    res = req.execute()
  File "/Users/netomi/Desktop/msgai-data-analyst-code/venv-botperf/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/netomi/Desktop/msgai-data-analyst-code/venv-botperf/lib/python3.9/site-packages/googleapiclient/http.py", line 922, in execute
    resp, content = _retry_request(
  File "/Users/netomi/Desktop/msgai-data-analyst-code/venv-botperf/lib/python3.9/site-packages/googleapiclient/http.py", line 190, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/Users/netomi/Desktop/msgai-data-analyst-code/venv-botperf/lib/python3.9/site-packages/google_auth_httplib2.py", line 209, in request
    self.credentials.before_request(self._request, method, uri, request_headers)
  File "/Users/netomi/Desktop/msgai-data-analyst-code/venv-botperf/lib/python3.9/site-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/Users/netomi/Desktop/msgai-data-analyst-code/venv-botperf/lib/python3.9/site-packages/google/oauth2/service_account.py", line 410, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "/Users/netomi/Desktop/msgai-data-analyst-code/venv-botperf/lib/python3.9/site-packages/google/oauth2/_client.py", line 199, in jwt_grant
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.RefreshError: ('No access token in response.', {'id_token':"...yN7mFGr1_7_CCAiqFVqzDw...'})

```

**Comment by sai-sunder-s** [comment]
What google_credentials are you using? From [this code](https://github.com/googleapis/google-auth-library-python/blob/6f49d1fa1dff62c5f2ed0cf198507568f5c4296f/google/oauth2/service_account.py#L664), it looks like you should have created IDTokenCredentials if you are going to be using id token.

**Comment by clundin25** [comment]
I am closing this as it has gone stale. Please re-open this if you should need further assistance @VisheshMangla2711 !
