### ISSUE TITLE
Explicit Credentials are ignored unless Env variables are set

### ISSUE THREAD

**Issue by DemonICOLI** [googleapis/google-auth-library-python#1287]
#### Environment details

  - OS: Docker (python:3.10-slim)
  - Python version: 3.10
  - `google-auth` version: 2.16+

#### Steps to reproduce

  1. Generate a set of credentials for AWS WIF
  2. Try to explicit pass the credentials to a client without setting GCLOUD_PROJECT nor GOOGLE_APPLICATION_CREDENTIALS

Hey, 

I'm testing a WIF flow for AWS, however, any client will fail with the following error even if i'm passing the credentials explicitly.

` raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
2023-05-07T00:01:25.981694803Z google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
`

in order to test this in a clean environment, the test was done under docker.

the code is the following

```
from google.auth import aws
from google.cloud import storage



creds = aws.Credentials.from_info({"type": "external_account",
                                   "audience": "<my-audience>",
                                   "subject_token_type": "urn:ietf:params:aws:token-type:aws4_request",
                                   "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/<sa-email>:generateAccessToken",
                                   "token_url": "https://sts.googleapis.com/v1/token",
                                   "credential_source": {"environment_id": "aws1",
                                                         "regional_cred_verification_url": "https://sts.{region}.amazonaws.com?Action=GetCallerIdentity&Version=2011-06-15"}})
scoped_credentials = creds.with_scopes(['https://www.googleapis.com/auth/cloud-platform'])
client = storage.Client(credentials=scoped_credentials)
buckets = client.list_buckets(project='my_project')
for bucket in buckets:
    print(bucket.name)
```

just adding the envs with any value will work (the GOOGLE_APPLICATION_CREDENTIALS file must exists, even empty)

**Comment by clundin25** [comment]
@DemonICOLI Can you share a stacktrace that identifies the source of the exception?

It seems the client may be trying to use `default` to acquire credentials.

**Comment by DemonICOLI** [comment]
Hey @clundin25,

Here is the full stack trace, i'm using storage as a test, but this happens as well in other apis such as aiplatform:

```
Traceback (most recent call last):
2023-05-12T03:58:33.439779005Z   File "//ttest.py", line 7, in <module>
2023-05-12T03:58:33.439809922Z     client = storage.Client(credentials=scoped_credentials)
2023-05-12T03:58:33.439854755Z   File "/usr/local/lib/python3.10/site-packages/google/cloud/storage/client.py", line 173, in __init__
2023-05-12T03:58:33.439868672Z     super(Client, self).__init__(
2023-05-12T03:58:33.439876505Z   File "/usr/local/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 320, in __init__
2023-05-12T03:58:33.440048463Z     _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
2023-05-12T03:58:33.440125005Z   File "/usr/local/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 268, in __init__
2023-05-12T03:58:33.441943755Z     project = self._determine_default(project)
2023-05-12T03:58:33.442027463Z   File "/usr/local/lib/python3.10/site-packages/google/cloud/client/__init__.py", line 287, in _determine_default
2023-05-12T03:58:33.442053213Z     return _determine_default_project(project)
2023-05-12T03:58:33.442067172Z   File "/usr/local/lib/python3.10/site-packages/google/cloud/_helpers/__init__.py", line 152, in _determine_default_project
2023-05-12T03:58:33.442108088Z     _, project = google.auth.default()
2023-05-12T03:58:33.442126755Z   File "/usr/local/lib/python3.10/site-packages/google/auth/_default.py", line 648, in default
2023-05-12T03:58:33.442139130Z     raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
2023-05-12T03:58:33.442147130Z google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
```

**Comment by clundin25** [comment]
Hi @DemonICOLI,

Thanks for the stacktrace! I believe you can pass your desired project into the [Client constructor](https://github.com/googleapis/python-storage/blob/main/google/cloud/storage/client.py#LL115C9-L115C16)

```py
client = storage.Client(credentials=scoped_credentials, project='my_project')
```

Alternatively you can create ADC credentials as per https://cloud.google.com/docs/authentication/external/set-up-adc.

**Comment by DemonICOLI** [comment]
i'll try and set up the project name, ADC is not really a solution here, as i currently have a pool of explicit credentials to choose from, and ADC just limit that to one set

**Comment by DemonICOLI** [comment]
I can confirm that setting the project name indeed fixes the issue with the explicit credentials, Thanks @clundin25 .

It may be worth adding this to the documentation, or if possible a patch, so project can be specified at operation level instead.

Thanks and Feel free to close the issue

**Comment by clundin25** [comment]
Here is a link to the documentation https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.client.Client!
