### ISSUE TITLE
Credentials.refresh() fails with TypeError when using $GOOGLE_AUTHENTICATION_CREDENTIALS

### ISSUE THREAD

**Issue by Nikratio** [googleapis/google-auth-library-python#319]
### Environment details

  - OS: Linux (Debian stable)
  - Python version: 3.5
  - pip version: 9.0.1
  - `google-auth` version: 1.6.2

#### Steps to reproduce

 1. Create new service account on https://console.cloud.google.com/
 2. Export the private key in JSON format
 3. Point `$GOOGLE_APPLICATION_CREDENTIALS` at it 
 4. Try to get an access token:

```
$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.auth.transport.requests
>>> import google.auth
>>> adc, project = google.auth.default()
>>> requestor = google.auth.transport.requests.Request()
>>> adc, project = google.auth.default(requestor)
>>> adc.refresh(requestor)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nikratio/.local/lib/python3.5/site-packages/google/oauth2/service_account.py", line 320, in refresh
    assertion = self._make_authorization_grant_assertion()
  File "/home/nikratio/.local/lib/python3.5/site-packages/google/oauth2/service_account.py", line 305, in _make_authorization_grant_assertion
    'scope': _helpers.scopes_to_string(self._scopes or ())
  File "/home/nikratio/.local/lib/python3.5/site-packages/google/auth/_helpers.py", line 186, in scopes_to_string
    return ' '.join(scopes)
TypeError: can only join an iterable
>>> 
```

Excerpts from the `$GOOGLE_APPLICATION_CREDENTIALS` file:

```
$ cat $GOOGLE_APPLICATION_CREDENTIALS 
{
  "type": "service_account",
  "project_id": "personal-NNN",
  "private_key_id": "snip",
  "private_key": "-----BEGIN PRIVATE KEY-----snip\n-----END PRIVATE KEY-----\n",
  "client_email": "xxxxxx@personal-NNNiam.gserviceaccount.com",
  "client_id": "NNN",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/XXXXXX.iam.gserviceaccount.com"
}
```

**Comment by eugenewf** [comment]
Looks like the signature for default expects the first positional arg to be the scopes.
> def default(scopes=None, request=None):
https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/_default.py#L220

Try adding the scopes and you should get past the join error. For example:
>>> adc, project = google.auth.default(scopes=['https://www.googleapis.com/auth/logging.write'], request=requestor)

**Comment by Nikratio** [comment]
Right, thanks!
