### ISSUE TITLE
SSLEOFError 

### ISSUE THREAD

**Issue by erickertz** [googleapis/google-auth-library-python#335]
#### Environment details

  - OS: Alpine3.9
 - OpenSSL: 1.1.1a
  - Python version: 2.7.15
  - pip version: 19.0.3
  - `google-auth` version: 1.6.3
 - `google-cloud-pubsub` version: 0.33.1

#### Steps to reproduce

  1. I only see this error when sending a high volume of messages to PubSub from my Python Celery application. Under high volumes I am seeing a steady log of the following error:

`[2018-10-23 09:07:41,061: ERROR/MainProcess] AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7facc99ad390>" raised exception!
Traceback (most recent call last):
  File "/opt/python2.7/lib/python2.7/site-packages/grpc/_plugin_wrapping.py", line 79, in __call__
    callback_state, callback))
  File "/opt/python2.7/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 77, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/opt/python2.7/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 65, in _get_authorization_headers
    headers)
  File "/opt/python2.7/lib/python2.7/site-packages/google/auth/credentials.py", line 122, in before_request
    self.refresh(request)
  File "/opt/python2.7/lib/python2.7/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/opt/python2.7/lib/python2.7/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/opt/python2.7/lib/python2.7/site-packages/google/oauth2/_client.py", line 106, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/opt/python2.7/lib/python2.7/site-packages/google/auth/transport/requests.py", line 124, in __call__
    six.raise_from(new_exc, caught_exc)
  File "/opt/python2.7/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:661)'),))`

This was mentioned here a while back:

https://github.com/googleapis/google-auth-library-python/issues/192#issuecomment-386290174

At the time I had an older OS and OpenSSL version. An upgrade was done but the error is still occurring.

Thanks for any help!

**Comment by erickertz** [comment]
I'm going to close this, it does seem that after updating to :

OS: Alpine3.9
OpenSSL: 1.1.1a

The problem has resolved.
