### ISSUE TITLE
google-cloud-logging==1.14.0 + google-auth==1.11.2 raise an Exception

### ISSUE THREAD

**Issue by ramonmedeiros** [googleapis/google-auth-library-python#454]
#### Environment details

  - OS: `python:3.8-alpine`
  - Python version: `python:3.8`
  - pip version: `19.3.1`
  - `google-auth` version: `google-auth==1.11.2`

#### Steps to reproduce

  1. With the following packages, send some logs to Stackdriver
  2. After script finishes, following message is displayed
```
Program shutting down, attempting to send 1 queued log entries to Stackdriver Logging...
Waiting up to 5 seconds.
AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7fc1e4042490>" raised exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/grpc/_plugin_wrapping.py", line 77, in __call__
    self._metadata_plugin(
  File "/usr/local/lib/python3.8/site-packages/google/auth/transport/grpc.py", line 87, in __call__
    future = self._pool.submit(self._get_authorization_headers, context)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 179, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
```

**Comment by busunkim96** [comment]
@ramonmedeiros Are you experiencing this error after upgrading google-auth? Or were you experiencing this previously?

The error message looks related to the issue reported #455. It may be worth downgrading to 1.7.1.
