### ISSUE TITLE
 ImportError: No module named 'requests.packages'

### ISSUE THREAD

**Issue by AAverin** [googleapis/google-auth-library-python#471]
After update to latest version we get
```
 from google.auth.transport.requests import AuthorizedSession
  File "/home/travis/.local/lib/python3.4/site-packages/google/auth/transport/requests.py", line 38, in <module>
    from requests.packages.urllib3.util.ssl_ import (
ImportError: No module named 'requests.packages'
```
Were there any changes made to the dependencies of the library?

These is our setup:
```
pip3 install --user google-cloud
pip3 install --user --upgrade pip
pip3 install --user requests
pip3 install --user google-auth
```

**Comment by busunkim96** [comment]
@AAverin Would you mind doing a pip freeze so we can see version #s for other dependencies?

@arithmetic1728 Is there an additional package that needs to be installed for the SSL support?

**Comment by arithmetic1728** [comment]
@AAverin what is the version of your `requests` library? I tried python3.4 on my machine, it worked fine.

```
(tmp) sijunliu@penguin:~/wks/tmp$ python -m pip freeze
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).                                          
cachetools==3.1.1
certifi==2019.11.28
chardet==3.0.4
google-auth==1.12.0
idna==2.8
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.21.0
rsa==4.0
six==1.14.0
urllib3==1.24.3

(tmp) sijunliu@penguin:~/wks/tmp$ python
Python 3.4.9 (default, Mar 26 2020, 14:10:47) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.auth.transport.requests import AuthorizedSession
>>>
```

**Comment by AAverin** [comment]
I can try checking, but because this was on CI and it was important to fix fast, I just rolled back to 1.11.3 and it resolved the issue

@arithmetic1728 Because I don't force specific versions, I would assume that latest version of `requests` library is being installed

**Comment by arithmetic1728** [comment]
@AAverin hmm... I am not sure what causes the problem. I tried python 3.4, 3.6, 3.7, none of them have problems on my machine. I think I will just change the lib to import ssl only when needed then.

@busunkim96 I created a PR to import ssl from `requests` only when needed. Please take a look. Thanks.

**Comment by busunkim96** [comment]
I'm also unable to reproduce this on my machine in a clean virtualenv.

Could you check which version of requests and urllib3 is being installed? `requests.packages` has been around [for a few years](https://github.com/psf/requests/blob/master/requests/packages.py). See https://github.com/psf/requests/issues/4071

This is unrelated to the issue, but we strongly recommend you upgrade to the separate google-cloud-* packages. The google-cloud package hasn't been updated in quite some time now.

**Comment by AAverin** [comment]
I was also unable to reproduce it on my macos, but travis CI failes.
I can add some debug commands to my CI script to debug.
I will do `python -m pip freeze` today, anything else that could help find the problem?

From what I have found, the only thing that changed was release of 1.12.0 on 25 of March and our CI started failing with that error.

**Comment by AAverin** [comment]
```
python3 is already the newest version (3.4.0-0ubuntu2).
The following additional packages will be installed:
  python-chardet-whl python-colorama-whl python-distlib-whl
  python-html5lib-whl python-pip-whl python-requests-whl python-setuptools-whl
  python-six-whl python-urllib3-whl python3-chardet python3-colorama
  python3-distlib python3-html5lib python3-pkg-resources python3-requests
  python3-setuptools python3-six python3-urllib3
Suggested packages:
  python3-genshi python3-lxml
Recommended packages:
  python3-wheel
The following NEW packages will be installed:
  python-chardet-whl python-colorama-whl python-distlib-whl
  python-html5lib-whl python-pip-whl python-requests-whl python-setuptools-whl
  python-six-whl python-urllib3-whl python3-chardet python3-colorama
  python3-distlib python3-html5lib python3-pip python3-pkg-resources
  python3-requests python3-setuptools python3-six python3-urllib3
```

```
[0K$ python -m pip freeze
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
apt-xapian-index==0.45
boto==2.20.1
bzr==2.7.0.dev1
chardet==2.0.1
Cheetah==2.4.4
cloud-init==0.7.5
configobj==4.7.2
crcmod==1.7
google-compute-engine==2.2.4
jsonpatch==1.3
jsonpointer==1.0
Landscape-Client==14.12
mercurial==4.2.2
oauth==1.0.1
PAM==0.4.2
prettytable==0.7.2
pycurl==7.19.3
pyOpenSSL==0.13
pyserial==2.6
python-apt===0.9.3.5ubuntu2
python-debian===0.1.21-nmu2ubuntu2
PyYAML==3.10
requests==2.2.1
six==1.5.2
ssh-import-id==3.21
Twisted-Core==13.2.0
Twisted-Names==13.2.0
Twisted-Web==13.2.0
urllib3==1.7.1
virtualenv==15.1.0
zope.interface==4.0.5
```

**Comment by AAverin** [comment]
So because both python and python3, and pip and pip3 are installed on the server, I should probably somehow give you guys log for python3, because pip3 is what is used to run everything and then script later is also ran with python3

**Comment by AAverin** [comment]
Looks like not that straighforward.
`python3 is already the newest version (3.4.0-0ubuntu2).`

For some reason freeze fails requiring pytnon3.5
```
Testing python3 -m pip freeze
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/.local/lib/python3.4/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/home/travis/.local/lib/python3.4/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/travis/.local/lib/python3.4/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/travis/.local/lib/python3.4/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/travis/.local/lib/python3.4/site-packages/pip/_internal/cli/cmdoptions.py", line 28, in <module>
    from pip._internal.models.target_python import TargetPython
  File "/home/travis/.local/lib/python3.4/site-packages/pip/_internal/models/target_python.py", line 4, in <module>
    from pip._internal.utils.misc import normalize_version_info
  File "/home/travis/.local/lib/python3.4/site-packages/pip/_internal/utils/misc.py", line 20, in <module>
    from pip._vendor import pkg_resources
  File "/home/travis/.local/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 92, in <module>
    raise RuntimeError("Python 3.5 or later is required")
RuntimeError: Python 3.5 or later is required
Done python3 -m pip freeze
```

I am not at all into python so if you need more info from me could use your guidance

**Comment by AAverin** [comment]
Closing as it seems that upgrading requests is the right solution
