### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by Bardo-Konrad** [googleapis/google-auth-library-python#531]
I am trying to install the google-api-python-client using `pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib`. This is what I got:

```
pi@himbeerkuchen:~ $ pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
Downloading/unpacking google-api-python-client
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 292, in find_requirement
    elif is_prerelease(version) and not (self.allow_all_prereleases or req.prereleases):
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 739, in is_prerelease
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable

Storing debug log for failure in /home/pi/.pip/pip.log
```

#### Environment details

  - OS: Raspian Jessie
  - Python version: 2.7
  - pip version: 1.5.6
  - `google-auth` version: current

#### Steps to reproduce

See above.

**Comment by busunkim96** [comment]
It looks like something is going wrong at the pip level. It looks like you have a old version of pip, so you may want to try an upgrade: `pip install --upgrade pip`

And if you are able to, please use Python 3. 😄

**Comment by Bardo-Konrad** [comment]
```
pi@himbeerkuchen:~ $ pip install --upgrade pip
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1097, in prepare_files
    req_to_install, self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 292, in find_requirement
    elif is_prerelease(version) and not (self.allow_all_prereleases or req.prereleases):
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 739, in is_prerelease
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable

Storing debug log for failure in /home/pi/.pip/pip.log

```

**Comment by busunkim96** [comment]
Can you try the solution [here](https://unix.stackexchange.com/questions/206121/pip-install-gives-typeerror-int-object-is-not-iterable)?

```
sudo apt-get install python3-pip
```

**Comment by parthea** [comment]
I'm going to close this issue due to inactivity but please feel free to re-open it if the issue still appears.
