### ISSUE TITLE
Python 3.4 not working with rsa version upgrade

### ISSUE THREAD

**Issue by aabmass** [googleapis/google-auth-library-python#548]
#### Environment details

  - OS: Linux
  - Python version: 3.4
  - pip version: 19.1.1
  - `google-auth` version: 1.18.0

#### Steps to reproduce

```sh
python3.4 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install google-auth

# importing google auth causes the issue
python -c "import google.auth.crypt"
Traceback (most recent call last):
  File "/usr/local/google/home/aaronabbott/tmp/venv3.4/lib/python3.4/site-packages/google/auth/crypt/rsa.py", line 20, in <module>
    from google.auth.crypt import _cryptography_rsa
  File "/usr/local/google/home/aaronabbott/tmp/venv3.4/lib/python3.4/site-packages/google/auth/crypt/_cryptography_rsa.py", line 22, in <module>
    import cryptography.exceptions
ImportError: No module named 'cryptography'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/google/home/aaronabbott/tmp/venv3.4/lib/python3.4/site-packages/google/auth/crypt/__init__.py", line 43, in <module>
    from google.auth.crypt import rsa
  File "/usr/local/google/home/aaronabbott/tmp/venv3.4/lib/python3.4/site-packages/google/auth/crypt/rsa.py", line 27, in <module>
    from google.auth.crypt import _python_rsa
  File "/usr/local/google/home/aaronabbott/tmp/venv3.4/lib/python3.4/site-packages/google/auth/crypt/_python_rsa.py", line 28, in <module>
    import rsa
  File "/usr/local/google/home/aaronabbott/tmp/venv3.4/lib/python3.4/site-packages/rsa/__init__.py", line 24, in <module>
    from rsa.key import newkeys, PrivateKey, PublicKey
  File "/usr/local/google/home/aaronabbott/tmp/venv3.4/lib/python3.4/site-packages/rsa/key.py", line 35, in <module>
    import typing
ImportError: No module named 'typing'
```

[rsa 4.1 drops python 2 and 3.4 support](https://github.com/sybrenstuvel/python-rsa#major-changes-in-41). The new version that google-auth is using tries to import `typing`.

**Comment by busunkim96** [comment]
Thanks for filing an issue! Given that 3.4 is now EOL I opened #549 to drop it from our list of supported versions. I also tweaked #544 to make the pin on RSA more specific

**Comment by aabmass** [comment]
Awesome, thank you for the quick response!

**Comment by tseaver** [comment]
Via #544.
