### ISSUE TITLE
google.auth.exceptions.RefreshError: The credentials do not contain the necessary fields need to refresh the access token. You must specify refresh_token, token_uri, client_id, and client_secret.

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-auth-library-python#659]
Thanks for stopping by to let us know something could be better!

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: 11.1
  - Python version: 3.8.5
  - pip version: pip 20.2.4 
  - `google-auth` version: 1.23.0

#### Steps to reproduce

  1. Saved google credentials and user token to separate file and a db
  2. when print(credentials), all of them are present yet the error shows that they don't.

### Code:

```
@blueprint.route("Calendar", methods=['GET', 'POST'])
def Calendar():
    user = User.query.filter_by(email=email).first()  
    
    with open('client_secret.json') as d:
        d = json.load(d)
    thecredentials = { 
        'client_id': d['web']['client_id'],
        'client_secret':d['web']['client_secret'],
        'refresh_token':None,
        'scopes':None,
        'token':user.token,
        'token_uri':d['web']['token_uri']
    }
    print(thecredentials) #prints all the credentials successfully 
    credentials = google.oauth2.credentials.Credentials(
        **credentials)
    thecredentials = credentials_to_dict(credentials)
    print(credentials)
    startTime = datetime.now(timezone.utc).astimezone().isoformat()
    print(startTime)
    utc_dt = datetime.now(timezone.utc).astimezone().isoformat()
    service = build('calendar', 'v3', credentials=credentials)
    events_result =service.calendarList().list().execute()

def credentials_to_dict(credentials):
      return {'token': credentials.token,
          'refresh_token': credentials.refresh_token,
          'token_uri': credentials.token_uri,
          'client_id': credentials.client_id,
          'client_secret': credentials.client_secret,
          'scopes': credentials.scopes}

```

Error:
```
Traceback (most recent call last):
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Daniyal/Startup/Website/app/base/routes.py", line 407, in Calendar
    events_result =service.calendarList().list().execute()
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/googleapiclient/http.py", line 900, in execute
    resp, content = _retry_request(
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/googleapiclient/http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/google_auth_httplib2.py", line 216, in request
    self.credentials.refresh(self._request)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/google/oauth2/credentials.py", line 194, in refresh
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: The credentials do not contain the necessary fields need to refresh the access token. You must specify refresh_token, token_uri, client_id, and client_secret.
```

Thanks!

**Comment by DaniyalDhz** [comment]
and if I add:

```
credentials = credentials_to_dict(credentials)
def credentials_to_dict(credentials):
      return {'token': credentials.token,
          'refresh_token': credentials.refresh_token,
          'token_uri': credentials.token_uri,
          'client_id': credentials.client_id,
          'client_secret': credentials.client_secret,
          'scopes': credentials.scopes}

```
I get:
```
Traceback (most recent call last):
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Daniyal/Startup/Website/app/base/routes.py", line 407, in Calendar
    service = build('calendar', 'v3', credentials=credentials)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/googleapiclient/discovery.py", line 278, in build
    service = build_from_document(
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/googleapiclient/discovery.py", line 540, in build_from_document
    http = _auth.authorized_http(credentials)
  File "/Users/Daniyal/Startup/Website/env/lib/python3.8/site-packages/googleapiclient/_auth.py", line 119, in authorized_http
    return credentials.authorize(build_http())
AttributeError: 'dict' object has no attribute 'authorize'
```

**Comment by DaniyalDhz** [comment]
I believe my mistake is with user token changing almost every time which contradicts what the code snippet recommended to do:
```
# ACTION ITEM: In a production app, you likely want to save these
    #              credentials in a persistent database instead.
    credentials = flow.credentials
    flask.session['credentials'] = credentials_to_dict(credentials)

```
Why save credentials to a persistent db if user token going to change every time?

**Comment by DaniyalDhz** [comment]
Update: 
After digging deeper through the [docs](https://developers.google.com/identity/protocols/oauth2#5.-refresh-the-access-token,-if-necessary.), I realized the developer most likely meant to save the refresh token to a db as they have a much longer life.

However, my credentials is like this:

{
  'client_id': '3118..vc2n.apps.googleusercontent.com',
  'client_secret': 'imMySiOXTb...R2w',
  'refresh_token': None,
  'scopes': None,
  'token': 'ya29.a0Af...Oyi4JLHqi',
  'token_uri': 'https://oauth2.googleapis.com/token'
}
I can't find any docs or code snippet on how to retrieve refresh token as a comment on [SO](https://stackoverflow.com/questions/26048945/oauth-v2-google-api-expiry-access-token) said too.

**Comment by busunkim96** [comment]
Hi @DaniyalDhz,

Your understanding is correct, you need a refresh token for the credential to be refreshable. The refresh token is returned the first time the [OAuth2 access tokens](https://developers.google.com/identity/protocols/oauth2/web-server#obtainingaccesstokens) are obtained. You should save it so you are able to refresh the token.

There is no way to go from an access token -> refresh token. You'll need to get the refresh token by going through the oauth2 flow again.

https://developers.google.com/identity/protocols/oauth2/web-server#offline
https://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token

**Comment by DaniyalDhz** [comment]
Got it! Thanks for sharing the useful resources! 
then my 2 questions left are:

1. if I have an outdated `access token` but a new and lasting `refresh token` would the API calls be successful (& not care about the access token) or not as the calendar API `build('calendar', 'v3', credentials=credentials)` takes all and I assume others do too. if it does care & reads access token, how shall I go about it?
2. I know refresh token are finite but last much longer. Thus, in case it does refresh, which prompts the user to reauthenticate the app manually, on the backend side, I shall check if a new refresh token is provided, if so save it immediately to db. Right?

**Comment by DaniyalDhz** [comment]
1. ok so back to my example where POST calls are made from chrome extension to the server that the user authenticated or in other words the user is not in the session(as most of the dev code I saw was all integrated with session & redirects). Should the code be something like this?

```
@blueprint.route("Calendar", methods=['POST'])
def Calendar():

    flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
      CLIENT_SECRETS_FILE, scopes=SCOPES)
    authorization_url, state = flow.authorization_url(
      # Enable offline access so that you can refresh an access token without
      # re-prompting the user for permission. Recommended for web server apps.
      access_type='offline',
      # Enable incremental authorization. Recommended as a best practice.
      include_granted_scopes='true')

    user = User.query.filter_by(email=email).first()  
    with open('client_secret.json') as d:
        d = json.load(d)
    thecredentials = { 
        'client_id': d['web']['client_id'],
        'client_secret':d['web']['client_secret'],
        'refresh_token':user.refresh,
        'scopes':None,
        'token':user.token,
        'token_uri':d['web']['token_uri']
    }
  service = build('calendar', 'v3', credentials=credentials)
```
As I don't see how the flow is updating the credentials unless I add:
```
flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(
        CLIENT_SECRETS_FILE, scopes=None, state=state)
    flow.redirect_uri = flask.url_for('base_blueprint.oauth2callback', _external=True)

    authorization_response = flask.request.url
    flow.fetch_token(authorization_response=authorization_response)
    credentials = flow.credentials
    flask.session['credentials'] = credentials_to_dict(credentials)

```   
per the doc which would defeat the POST call

**Comment by DaniyalDhz** [comment]
bottom line, I am not sure how to integrate the refresh access token offline with credentials all in one function.

**Comment by behai-nguyen** [comment]
> bottom line, I am not sure how to integrate the [refresh access token offline](https://developers.google.com/identity/protocols/oauth2/web-server#offline) code with credentials all in one function.

Hi @Daniyaldehleh,

How did you go about it finally, please?

Thank you and best regards,

...behai.
