### ISSUE TITLE
Docs haven't been published for google-auth > 1.22.0

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-auth-library-python#709]
https://googleapis.dev/python/google-auth/latest/ is stil https://googleapis.dev/python/google-auth/1.22.0/. Current library version is 1.27.0.

Fix the docs job and publish 1.27.0.

**Comment by busunkim96** [comment]
```
docuploader > Okay, I'm sending them to the cloud™ now.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/h/.local/lib/python3.8/site-packages/docuploader/__main__.py", line 199, in <module>
    main()
  File "/h/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/h/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/h/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/h/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/h/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/h/.local/lib/python3.8/site-packages/docuploader/__main__.py", line 138, in upload
    docuploader.upload.upload(
  File "/h/.local/lib/python3.8/site-packages/docuploader/upload.py", line 32, in upload
    bucket_ = client.get_bucket(bucket)
  File "/h/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 401, in get_bucket
    bucket = self._bucket_arg_to_bucket(bucket_or_name)
  File "/h/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 239, in _bucket_arg_to_bucket
    bucket = Bucket(self, name=bucket_or_name)
  File "/h/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 583, in __init__
    name = _validate_name(name)
  File "/h/.local/lib/python3.8/site-packages/google/cloud/storage/_helpers.py", line 66, in _validate_name
    if not all([name[0].isalnum(), name[-1].isalnum()]):
IndexError: string index out of range
================================================================
2021-02-26T01:12:32Z: Build finished with 1 
================================================================
```

**Comment by busunkim96** [comment]
1.27.0 has been published, will work on backfiling the rest later today.

**Comment by parthea** [comment]
I'm going to close this issue as obsolete but please feel free to re-open it.
