### ISSUE TITLE
FROM credentials_from_clientsecrets_and_code ( oauth2client) TO google-auth

### ISSUE THREAD

**Issue by MarcoMatta** [googleapis/google-auth-library-python#758]
My code is: 

```
from oauth2client import client

code = auth.get("code") #'4/0AY0e-g61t-GLn16f7ShbFJCdrqy6_TOZquBEIQcUyK-ASgQkQAGc2aNfKZhoFhDZ0S3PTw'
credentials = client.credentials_from_clientsecrets_and_code(
        CLIENT_SECRET_FILE,
        ["https://www.googleapis.com/auth/business.manage",
         "https://www.googleapis.com/auth/plus.business.manage"],
        code)
c = json.loads(credentials.to_json())
auth["credentials"] = c
auth_data = {"access_token": c.get("access_token"), "refresh_token": c.get("refresh_token"), "name": auth["name"]}
```

I need to update it, the flow is this https://developers.google.com/identity/sign-in/web/server-side-flow but the documentation is old.

I'm jumping from one page to another and more I read and less I understand.

Then I need to understand how get a new access_token, now my code is

```
payload = f'client_id={client_id}&client_secret={client_secret}&refresh_token={refresh_token}&grant_type=refresh_token'
headers = {'Content-Type': 'application/x-www-form-urlencoded'}
response = request("POST", "https://oauth2.googleapis.com/token", headers=headers, data=payload)
access_token = response.json().get("access_token")
```

I would like to use the client lib because I use the api to retrieve reviews from google my business but there is many bug in google api ( empty reviews, problems with auth for some users) and I want to exlude all possible problems related to authentication.

The documentation is useless.

Thanks

**Comment by MarcoMatta** [comment]
I tryed this code 
```
import os
from google_auth_oauthlib.flow import Flow

basedir = os.path.abspath(os.path.dirname(__file__))
CLIENT_SECRET_FILE = os.path.join(basedir, 'gapi.json')
code = '4/0AY0e-g7n---iHhZt_Lhve0HLVdYTIhCnD2KODIeWSjZ-tnwBHvgExm1O8VC67BPhf3TKJQ'
scopes = ["https://www.googleapis.com/auth/business.manage",
          "https://www.googleapis.com/auth/plus.business.manage"]
print(CLIENT_SECRET_FILE)

# Create the flow using the client secrets file from the Google API
# Console.
flow = Flow.from_client_secrets_file(CLIENT_SECRET_FILE, scopes=scopes)
credentials = flow.fetch_token(code=code)
print(credentials)
```

I get this errore:

```
Traceback (most recent call last):
  File "C:\JetBrains\Toolbox\apps\PyCharm-P\ch-0\211.7142.13\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\JetBrains\Toolbox\apps\PyCharm-P\ch-0\211.7142.13\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\google-mybusiness-api/from_code.py", line 14, in <module>
    credentials = flow.fetch_token(code=code)
  File "E:\google-mybusiness-api\venv\lib\site-packages\google_auth_oauthlib\flow.py", line 288, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
  File "E:\google-mybusiness-api\venv\lib\site-packages\requests_oauthlib\oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "E:\google-mybusiness-api\venv\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "E:\google-mybusiness-api\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "E:\google-mybusiness-api\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "E:\google-mybusiness-api\venv\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Missing parameter: redirect_uri
python-BaseException
```

**Comment by busunkim96** [comment]
Hi @MarcoMatta,

https://developers.google.com/identity/protocols/oauth2/web-server#python_6 has the most up-to-date and thorough end-to-end example for web-server (it shows an example Flask App).

If you're running a script locally, the [Installed App Flow](https://googleapis.dev/python/google-auth-oauthlib/latest/reference/google_auth_oauthlib.flow.html#google_auth_oauthlib.flow.InstalledAppFlow) is easier to manage. 

> This Flow subclass makes it easier to perform the Installed Application Authorization Flow. This flow is useful for local development or applications that are installed on a desktop operating system.

https://developers.google.com/docs/api/quickstart/python#step_2_configure_the_sample is a full sample for the Google Docs API that uses the Installed App Flow in `google-auth-oauthlib`.

**Comment by MarcoMatta** [comment]
Solution: **redirect_uri="postmessage"**, I don't know why!

```
import os
from google_auth_oauthlib.flow import Flow
from requests import request

basedir = os.path.abspath(os.path.dirname(__file__))
CLIENT_SECRET_FILE = os.path.join(basedir, 'gapi.json')
code = "from gui"
scopes = ["https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/userinfo.email",
          "openid", "https://www.googleapis.com/auth/business.manage"]

flow = Flow.from_client_secrets_file(CLIENT_SECRET_FILE, scopes=scopes, redirect_uri="postmessage")
credentials = flow.fetch_token(code=code)
```

Some advice for refresh token?

**Comment by busunkim96** [comment]
Hi @MarcoMatta,


For the refresh token, you can get it through `credentials.refresh_token`. You should make sure to save it somewhere if you're looking to refresh the credentials.

If you're sending calls through the `requests` library, the Auth library provides an Authorized Session. If you use the session the auth header gets added automatically.

Here's a small snippet that will work for local development. 


```py
import os
import json

import google.oauth2.credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport import requests


basedir = os.path.abspath(os.path.dirname(__file__))
CLIENT_SECRET_FILE = os.path.join(basedir, "gapi.json")

scopes = [
    "https://www.googleapis.com/auth/userinfo.profile",
    "https://www.googleapis.com/auth/userinfo.email",
    "openid",
    "https://www.googleapis.com/auth/business.manage",
]

flow = InstalledAppFlow.from_client_secrets_file(CLIENT_SECRET_FILE, scopes=scopes,)

# Run the auth flow to get credentials
credentials = flow.run_console()

# Create an authorized session
session = requests.AuthorizedSession(credentials)

# Send requests through Authorized Session session
# The access token will automatically be added to the header
resp = session.get("...")  # TODO fill with desired URL


# Optional: Save the credentials for re-use
with open("token.json", "w") as token:
    token.write(credentials.to_json())
```

To reload the token, you would do:

```py
import google.oauth2.credentials

# Reload credentials from JSON file:
reloaded_credentials = google.oauth2.credentials.Credentials.from_authorized_user_file("token.json")
```

For web-server, https://developers.google.com/identity/protocols/oauth2/web-server is the up to date example using google-auth and google-auth-oauthlib.

**Comment by MarcoMatta** [comment]
I'm using https://developers.google.com/identity/sign-in/web/server-side-flow :

![immagine](https://user-images.githubusercontent.com/3217840/119617962-a60cc980-be02-11eb-8aed-a7c0b35d9463.png)

I have already **code** obtained from my react app during user login, and the server are stateless. Your answer not respond to my question, for example why I have to use **redirect_uri="postmessage"** and my code works?

I resolved my self!

I should to write documentation simpler and cleaner, It's very difficult to understand although I have confidence with oauth2 protocol!!

**Comment by busunkim96** [comment]
Ah sorry about that. I looked at your code snippet and assumed you were using the web-server flow.

Glad to hear you resolved it yourself. I'll file a bug asking for the code example on that page to be updated to google-auth.
